import {
  LayoutDashboard,
  UserCircle,
  Route,
  ShieldAlert,
  CheckCircle,
  FileText,
  Users,
  FolderOpen,
  Target,
  BookOpen,
  Info,
  Wrench,
  Layers,
  Bell,
  Inbox,
  ClipboardList,
  GitCompare,
  Calendar,
  FlaskConical,
  BarChart3,
  Brain,
  Shield,
  AlertTriangle,
  HeartPulse,
  Scale,
  ShieldCheck,
  HelpCircle,
  FileSpreadsheet,
  Upload,
  Cog,
  UserCog,
  GitBranch,
  Database,
  GraduationCap,
  LifeBuoy,
  HelpCircle as FallbackIcon,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  UserCircle,
  Route,
  ShieldAlert,
  CheckCircle,
  FileText,
  Users,
  FolderOpen,
  Target,
  BookOpen,
  Info,
  Wrench,
  Layers,
  Bell,
  Inbox,
  ClipboardList,
  GitCompare,
  Calendar,
  FlaskConical,
  BarChart3,
  Brain,
  Shield,
  AlertTriangle,
  HeartPulse,
  Scale,
  ShieldCheck,
  HelpCircle,
  FileSpreadsheet,
  Upload,
  Cog,
  UserCog,
  GitBranch,
  Database,
  GraduationCap,
  LifeBuoy,
};

/** Resolve an icon name string to a Lucide React component. */
export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? FallbackIcon;
}
