import { NextRequest } from "next/server";
import { getSessionUser } from "@/lib/auth";
import { getSetting } from "@/lib/settings";
import Anthropic from "@anthropic-ai/sdk";

export const dynamic = "force-dynamic";

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

interface ChatRequestBody {
  message: string;
  history: ChatMessage[];
  context: {
    page: string;
    userRole: string;
    userName: string;
  };
}

function buildSystemPrompt(userName: string, userRole: string, page: string): string {
  return `You are the Provisum Assistant, an AI helper embedded in the Provisum platform for enterprise security role mapping.

You are speaking with ${userName} (role: ${userRole}). They are currently on the "${page}" page.

Key platform concepts you should reference when relevant:
- **Personas**: Groups of users with similar access patterns, generated by AI analysis of source system data.
- **SOD Conflicts**: Segregation of Duties violations where incompatible permissions are assigned to the same role.
- **Target Roles**: The destination roles in the new system (e.g. S/4HANA) that source permissions are mapped to.
- **Approval Workflow**: Mapped roles go through a review chain — mapper submits, approver reviews, coordinator oversees.
- **Provisioning Alerts**: Flags for users who have more access than needed based on their actual usage patterns.
- **Releases**: Versioned snapshots of role mapping work that can be compared and promoted.

Guidelines:
- Be concise and action-oriented. Prefer short, helpful answers over long explanations.
- Respect the user's role boundaries. A viewer should not be guided to perform admin actions.
- If asked about something outside the platform's scope, politely redirect to platform-related assistance.
- Use markdown formatting sparingly — bold for emphasis, bullet lists for steps.
- When referencing platform pages, use their display names (Dashboard, Personas, Role Mapping, etc.).`;
}

export async function POST(req: NextRequest) {
  const user = getSessionUser();
  if (!user) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: { "Content-Type": "application/json" },
    });
  }

  let body: ChatRequestBody;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid request body" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const { message, history = [], context } = body;

  if (!message || typeof message !== "string") {
    return new Response(JSON.stringify({ error: "Message is required" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const apiKey = getSetting("ai.apiKey") || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return new Response(JSON.stringify({ error: "AI API key not configured" }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }

  const model = getSetting("ai.model") || "claude-sonnet-4-20250514";

  const systemPrompt = buildSystemPrompt(
    context?.userName || user.displayName,
    context?.userRole || user.role,
    context?.page || "unknown"
  );

  const messages: Anthropic.MessageParam[] = [
    ...history.map((msg) => ({
      role: msg.role as "user" | "assistant",
      content: msg.content,
    })),
    { role: "user" as const, content: message },
  ];

  try {
    const client = new Anthropic({ apiKey });

    const stream = client.messages.stream({
      model,
      max_tokens: 2048,
      system: systemPrompt,
      messages,
    });

    const readableStream = new ReadableStream({
      async start(controller) {
        const encoder = new TextEncoder();
        try {
          stream.on("text", (text) => {
            controller.enqueue(encoder.encode(`data: ${JSON.stringify({ text })}\n\n`));
          });

          stream.on("end", () => {
            controller.enqueue(encoder.encode("data: [DONE]\n\n"));
            controller.close();
          });

          stream.on("error", (error) => {
            console.error("Anthropic stream error:", error);
            controller.enqueue(
              encoder.encode(`data: ${JSON.stringify({ error: "Stream error" })}\n\n`)
            );
            controller.close();
          });
        } catch (error) {
          console.error("Stream setup error:", error);
          controller.enqueue(
            encoder.encode(`data: ${JSON.stringify({ error: "Failed to start stream" })}\n\n`)
          );
          controller.close();
        }
      },
    });

    return new Response(readableStream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      },
    });
  } catch (error) {
    console.error("Chat API error:", error);
    return new Response(
      JSON.stringify({ error: "Failed to connect to AI service" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
