import { NextRequest } from "next/server";
import { getSessionUser } from "@/lib/auth";
import { getSetting } from "@/lib/settings";
import { getDashboardStats } from "@/lib/queries";
import { getUserScope, getUserScopeDepartments } from "@/lib/scope";
import { db } from "@/db";
import * as schema from "@/db/schema";
import { inArray, sql } from "drizzle-orm";
import Anthropic from "@anthropic-ai/sdk";

export const dynamic = "force-dynamic";

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

interface ChatRequestBody {
  message: string;
  history: ChatMessage[];
  context: {
    page: string;
    userRole: string;
    userName: string;
  };
}

function getLumenDataContext(user: { id: number; role: string }): string {
  try {
    const stats = getDashboardStats();
    const scopedUserIds = getUserScope(user as Parameters<typeof getUserScope>[0]);
    const scopeDepts = getUserScopeDepartments(user as Parameters<typeof getUserScopeDepartments>[0]);

    const lines: string[] = [
      `\n## Current Project Data`,
      `- Total users: ${stats.totalUsers} (${stats.totalSourceRoles} source roles, ${stats.totalTargetRoles} target roles)`,
      `- Personas: ${stats.totalPersonas} generated, ${stats.totalGroups} consolidated groups`,
      `- Persona coverage: ${stats.usersWithPersona}/${stats.totalUsers} users assigned (${stats.totalUsers > 0 ? Math.round((stats.usersWithPersona / stats.totalUsers) * 100) : 0}%)`,
      `- Mapped: ${stats.personasWithMapping}/${stats.totalPersonas} personas have target role assignments`,
      `- Approved: ${stats.approvedAssignments}/${stats.totalAssignments} assignments approved`,
      `- SOD rules: ${stats.sodRulesCount} loaded`,
    ];

    const conflicts = stats.sodConflictsBySeverity;
    if (conflicts.length > 0) {
      lines.push(`- SOD conflicts: ${conflicts.map(c => `${c.count} ${c.severity}`).join(", ")}`);
    }
    if (stats.lowConfidence > 0) {
      lines.push(`- Low confidence assignments: ${stats.lowConfidence}`);
    }

    // Scoped context for non-admin roles
    if (scopedUserIds !== null) {
      lines.push(`\n## Your Scope`);
      lines.push(`- Departments: ${scopeDepts && scopeDepts.length > 0 ? scopeDepts.join(", ") : "None assigned"}`);
      lines.push(`- Users in your scope: ${scopedUserIds.length}`);

      if (scopedUserIds.length > 0) {
        const scopedPersonaCount = db
          .select({ count: sql<number>`count(distinct persona_id)` })
          .from(schema.userPersonaAssignments)
          .where(inArray(schema.userPersonaAssignments.userId, scopedUserIds))
          .get()?.count ?? 0;
        lines.push(`- Personas in your scope: ${scopedPersonaCount}`);
      }
    }

    return lines.join("\n");
  } catch {
    return "\n## Project Data\nUnable to load project statistics.";
  }
}

function buildSystemPrompt(userName: string, userRole: string, page: string, dataContext: string): string {
  return `You are Lumen, the Provisum AI assistant for enterprise security role mapping.

You are speaking with ${userName} (role: ${userRole}). They are currently on the "${page}" page.
${dataContext}

Key platform concepts:
- **Personas**: Groups of users with similar access patterns, generated by AI analysis.
- **SOD Conflicts**: Segregation of Duties violations where incompatible permissions are assigned.
- **Target Roles**: Destination roles in the new system that source permissions map to.
- **Approval Workflow**: Mapper submits → Approver reviews → Coordinator oversees.
- **Provisioning Alerts**: Flags for users with more access than needed.

Guidelines:
- Be concise and action-oriented. Use the project data above to give specific, quantified answers.
- When a user asks "how many", "what's left", or "what's the status" — answer with real numbers from the data.
- Respect the user's role boundaries. A viewer should not be guided to perform admin actions.
- If asked about something outside the platform, politely redirect.
- Use markdown sparingly — bold for emphasis, bullet lists for steps.
- Reference pages by name: Dashboard, Personas, Role Mapping, SOD Analysis, Approvals, Exports.`;
}

export async function POST(req: NextRequest) {
  const user = getSessionUser();
  if (!user) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: { "Content-Type": "application/json" },
    });
  }

  let body: ChatRequestBody;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid request body" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const { message, history = [], context } = body;

  if (!message || typeof message !== "string") {
    return new Response(JSON.stringify({ error: "Message is required" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const apiKey = getSetting("ai.apiKey") || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return new Response(JSON.stringify({ error: "AI API key not configured" }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }

  const model = getSetting("ai.model") || "claude-sonnet-4-20250514";

  const dataContext = getLumenDataContext(user);
  const systemPrompt = buildSystemPrompt(
    context?.userName || user.displayName,
    context?.userRole || user.role,
    context?.page || "unknown",
    dataContext
  );

  const messages: Anthropic.MessageParam[] = [
    ...history.map((msg) => ({
      role: msg.role as "user" | "assistant",
      content: msg.content,
    })),
    { role: "user" as const, content: message },
  ];

  try {
    const client = new Anthropic({ apiKey });

    const stream = client.messages.stream({
      model,
      max_tokens: 2048,
      system: systemPrompt,
      messages,
    });

    const readableStream = new ReadableStream({
      async start(controller) {
        const encoder = new TextEncoder();
        try {
          stream.on("text", (text) => {
            controller.enqueue(encoder.encode(`data: ${JSON.stringify({ text })}\n\n`));
          });

          stream.on("end", () => {
            controller.enqueue(encoder.encode("data: [DONE]\n\n"));
            controller.close();
          });

          stream.on("error", (error) => {
            console.error("Anthropic stream error:", error);
            controller.enqueue(
              encoder.encode(`data: ${JSON.stringify({ error: "Stream error" })}\n\n`)
            );
            controller.close();
          });
        } catch (error) {
          console.error("Stream setup error:", error);
          controller.enqueue(
            encoder.encode(`data: ${JSON.stringify({ error: "Failed to start stream" })}\n\n`)
          );
          controller.close();
        }
      },
    });

    return new Response(readableStream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      },
    });
  } catch (error) {
    console.error("Chat API error:", error);
    return new Response(
      JSON.stringify({ error: "Failed to connect to AI service" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
