import ExcelJS from "exceljs";
import { db } from "@/db";
import * as schema from "@/db/schema";
import { eq, count } from "drizzle-orm";

export async function generateExcelReport(generatedByUsername?: string): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Provisum";
  workbook.created = new Date();

  // ─────────────────────────────────────────────
  // Pre-fetch shared data
  // ─────────────────────────────────────────────
  const allUsers = db.select().from(schema.users).all();
  const allPersonas = db.select().from(schema.personas).all();
  const allRoles = db.select().from(schema.targetRoles).all();
  const allSodRules = db.select().from(schema.sodRules).all();
  const allConflicts = db.select().from(schema.sodConflicts).all();

  const totalAssignments = db.select({ count: count() }).from(schema.userTargetRoleAssignments).get()!.count;
  const approvedAssignments = db.select({ count: count() }).from(schema.userTargetRoleAssignments)
    .where(eq(schema.userTargetRoleAssignments.status, "approved")).get()!.count;
  const approvalPct = totalAssignments > 0 ? Math.round((approvedAssignments / totalAssignments) * 100) : 0;

  const totalMappings = db.select({ count: count() }).from(schema.personaTargetRoleMappings).get()!.count;

  // ─────────────────────────────────────────────
  // TAB 1: Cover Sheet
  // ─────────────────────────────────────────────
  const cover = workbook.addWorksheet("Cover Sheet");
  cover.getColumn("A").width = 35;
  cover.getColumn("B").width = 30;

  // Logo text block
  cover.addRow([]);
  const logoRow = cover.addRow(["PROVISUM"]);
  logoRow.font = { bold: true, size: 22, color: { argb: "FF1E293B" } };
  const subtitleRow = cover.addRow(["Enterprise Role Migration Platform"]);
  subtitleRow.font = { size: 12, italic: true, color: { argb: "FF64748B" } };
  cover.addRow([]);

  // Report title
  const reportTitleRow = cover.addRow(["Role Mapping Report"]);
  reportTitleRow.font = { bold: true, size: 16 };
  cover.addRow([]);

  // Generation info
  const dateRow = cover.addRow(["Report Generated", new Date().toLocaleString()]);
  dateRow.font = { size: 11 };
  if (generatedByUsername) {
    const byRow = cover.addRow(["Generated By", generatedByUsername]);
    byRow.font = { size: 11 };
  }
  cover.addRow([]);

  // Project summary
  const summaryTitle = cover.addRow(["Project Summary"]);
  summaryTitle.font = { bold: true, size: 14 };
  cover.addRow([]);

  const summaryHeader = cover.addRow(["Metric", "Value"]);
  summaryHeader.font = { bold: true };
  summaryHeader.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E293B" } };
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
  });
  cover.addRow(["Total Users", allUsers.length]);
  cover.addRow(["Total Personas", allPersonas.length]);
  cover.addRow(["Total Mappings", totalMappings]);
  cover.addRow(["Target Roles Available", allRoles.length]);
  cover.addRow(["Approval Rate", `${approvalPct}%`]);
  cover.addRow(["SOD Rules", allSodRules.length]);
  cover.addRow(["SOD Conflicts Detected", allConflicts.length]);
  cover.addRow([]);
  cover.addRow(["Sheets in this workbook:"]);
  cover.addRow(["  1. Cover Sheet"]);
  cover.addRow(["  2. Executive Summary"]);
  cover.addRow(["  3. User-Persona Mapping"]);
  cover.addRow(["  4. Persona-Role Mapping"]);
  cover.addRow(["  5. Full Mapping Chain"]);
  cover.addRow(["  6. SOD Conflicts"]);
  cover.addRow(["  7. Permission Gaps"]);

  // ─────────────────────────────────────────────
  // TAB 2: Executive Summary
  // ─────────────────────────────────────────────
  const execSummary = workbook.addWorksheet("Executive Summary");
  execSummary.getColumn("A").width = 30;
  execSummary.getColumn("B").width = 18;
  execSummary.getColumn("C").width = 18;
  execSummary.getColumn("D").width = 18;

  const execTitle = execSummary.addRow(["Executive Summary"]);
  execTitle.font = { bold: true, size: 16 };
  execSummary.addRow([]);

  // Key metrics section
  const metricsTitle = execSummary.addRow(["Key Metrics"]);
  metricsTitle.font = { bold: true, size: 13 };
  execSummary.addRow([]);

  const metricsHeader = execSummary.addRow(["Metric", "Count", "Status"]);
  metricsHeader.font = { bold: true };
  metricsHeader.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E293B" } };
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
  });

  execSummary.addRow(["Users Loaded", allUsers.length, allUsers.length > 0 ? "Complete" : "Pending"]);
  execSummary.addRow(["Personas Generated", allPersonas.length, allPersonas.length > 0 ? "Complete" : "Pending"]);
  execSummary.addRow(["Role Mappings", totalMappings, totalMappings > 0 ? "Complete" : "Pending"]);
  execSummary.addRow(["Total Assignments", totalAssignments, totalAssignments > 0 ? "Complete" : "Pending"]);
  execSummary.addRow(["Approved Assignments", approvedAssignments, approvalPct >= 80 ? "On Track" : "In Progress"]);
  execSummary.addRow(["Approval Rate", `${approvalPct}%`, approvalPct >= 80 ? "Healthy" : approvalPct >= 50 ? "Moderate" : "Needs Attention"]);
  execSummary.addRow([]);

  // Department breakdown
  const deptTitle = execSummary.addRow(["Department Breakdown"]);
  deptTitle.font = { bold: true, size: 13 };
  execSummary.addRow([]);

  const deptHeader = execSummary.addRow(["Department", "Users", "% of Total"]);
  deptHeader.font = { bold: true };
  deptHeader.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE2E8F0" } };
    cell.font = { bold: true };
  });

  const deptStats = db.select({
    department: schema.users.department,
    userCount: count(),
  }).from(schema.users).groupBy(schema.users.department).all();

  for (const dept of deptStats) {
    const pct = allUsers.length > 0 ? Math.round((dept.userCount / allUsers.length) * 100) : 0;
    execSummary.addRow([dept.department ?? "Unknown", dept.userCount, `${pct}%`]);
  }
  execSummary.addRow([]);

  // Risk summary — SOD conflicts by severity
  const riskTitle = execSummary.addRow(["Risk Summary — SOD Conflicts by Severity"]);
  riskTitle.font = { bold: true, size: 13 };
  execSummary.addRow([]);

  const riskHeader = execSummary.addRow(["Severity", "Count", "Resolution Status"]);
  riskHeader.font = { bold: true };
  riskHeader.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE2E8F0" } };
    cell.font = { bold: true };
  });

  if (allConflicts.length === 0) {
    execSummary.addRow(["No SOD conflicts detected", "", "LOW RISK"]);
  } else {
    const severityMap: Record<string, { total: number; open: number; accepted: number }> = {};
    for (const c of allConflicts) {
      const sev = c.severity ?? "unknown";
      if (!severityMap[sev]) severityMap[sev] = { total: 0, open: 0, accepted: 0 };
      severityMap[sev].total++;
      if (c.resolutionStatus === "open") severityMap[sev].open++;
      if (c.resolutionStatus === "risk_accepted") severityMap[sev].accepted++;
    }
    for (const [sev, stats] of Object.entries(severityMap)) {
      const statusParts: string[] = [];
      if (stats.open > 0) statusParts.push(`${stats.open} open`);
      if (stats.accepted > 0) statusParts.push(`${stats.accepted} accepted`);
      const resolved = stats.total - stats.open - stats.accepted;
      if (resolved > 0) statusParts.push(`${resolved} resolved`);
      execSummary.addRow([sev.charAt(0).toUpperCase() + sev.slice(1), stats.total, statusParts.join(", ")]);
    }
  }

  // ─────────────────────────────────────────────
  // TAB 3: User-Persona Mapping
  // ─────────────────────────────────────────────
  const sheet1 = workbook.addWorksheet("User-Persona Mapping");
  sheet1.columns = [
    { header: "User ID", key: "sourceUserId", width: 15 },
    { header: "Name", key: "displayName", width: 25 },
    { header: "Email", key: "email", width: 30 },
    { header: "Department", key: "department", width: 20 },
    { header: "Job Title", key: "jobTitle", width: 25 },
    { header: "Persona", key: "personaName", width: 25 },
    { header: "Confidence", key: "confidence", width: 12 },
    { header: "Group", key: "groupName", width: 25 },
  ];

  for (const user of allUsers) {
    const assignment = db.select({
      personaName: schema.personas.name,
      confidence: schema.userPersonaAssignments.confidenceScore,
      groupName: schema.consolidatedGroups.name,
    })
      .from(schema.userPersonaAssignments)
      .leftJoin(schema.personas, eq(schema.personas.id, schema.userPersonaAssignments.personaId))
      .leftJoin(schema.consolidatedGroups, eq(schema.consolidatedGroups.id, schema.personas.consolidatedGroupId))
      .where(eq(schema.userPersonaAssignments.userId, user.id))
      .get();

    sheet1.addRow({
      sourceUserId: user.sourceUserId,
      displayName: user.displayName,
      email: user.email,
      department: user.department,
      jobTitle: user.jobTitle,
      personaName: assignment?.personaName ?? "Unassigned",
      confidence: assignment?.confidence ?? null,
      groupName: assignment?.groupName ?? "",
    });
  }
  styleHeader(sheet1);

  // ─────────────────────────────────────────────
  // TAB 4: Persona-Target Role Mapping
  // ─────────────────────────────────────────────
  const sheet2 = workbook.addWorksheet("Persona-Role Mapping");
  sheet2.columns = [
    { header: "Persona", key: "personaName", width: 25 },
    { header: "Business Function", key: "businessFunction", width: 20 },
    { header: "Target Role ID", key: "targetRoleId", width: 15 },
    { header: "Target Role Name", key: "targetRoleName", width: 25 },
    { header: "Coverage %", key: "coveragePercent", width: 12 },
    { header: "Confidence", key: "confidence", width: 12 },
    { header: "Reason", key: "reason", width: 40 },
  ];

  const mappings = db.select({
    personaName: schema.personas.name,
    businessFunction: schema.personas.businessFunction,
    targetRoleId: schema.targetRoles.roleId,
    targetRoleName: schema.targetRoles.roleName,
    coveragePercent: schema.personaTargetRoleMappings.coveragePercent,
    confidence: schema.personaTargetRoleMappings.confidence,
    reason: schema.personaTargetRoleMappings.mappingReason,
  })
    .from(schema.personaTargetRoleMappings)
    .innerJoin(schema.personas, eq(schema.personas.id, schema.personaTargetRoleMappings.personaId))
    .innerJoin(schema.targetRoles, eq(schema.targetRoles.id, schema.personaTargetRoleMappings.targetRoleId))
    .all();

  for (const m of mappings) {
    sheet2.addRow(m);
  }
  styleHeader(sheet2);

  // ─────────────────────────────────────────────
  // TAB 5: Full Mapping Chain
  // ─────────────────────────────────────────────
  const sheet3 = workbook.addWorksheet("Full Mapping Chain");
  sheet3.columns = [
    { header: "User ID", key: "sourceUserId", width: 15 },
    { header: "User Name", key: "displayName", width: 25 },
    { header: "Department", key: "department", width: 20 },
    { header: "Persona", key: "personaName", width: 25 },
    { header: "Target Role", key: "targetRoleName", width: 25 },
    { header: "Assignment Type", key: "assignmentType", width: 18 },
    { header: "Status", key: "status", width: 18 },
  ];

  const fullChain = db.select({
    sourceUserId: schema.users.sourceUserId,
    displayName: schema.users.displayName,
    department: schema.users.department,
    personaName: schema.personas.name,
    targetRoleName: schema.targetRoles.roleName,
    assignmentType: schema.userTargetRoleAssignments.assignmentType,
    status: schema.userTargetRoleAssignments.status,
  })
    .from(schema.userTargetRoleAssignments)
    .innerJoin(schema.users, eq(schema.users.id, schema.userTargetRoleAssignments.userId))
    .innerJoin(schema.targetRoles, eq(schema.targetRoles.id, schema.userTargetRoleAssignments.targetRoleId))
    .leftJoin(schema.personas, eq(schema.personas.id, schema.userTargetRoleAssignments.derivedFromPersonaId))
    .all();

  for (const row of fullChain) {
    sheet3.addRow(row);
  }
  styleHeader(sheet3);

  // ─────────────────────────────────────────────
  // TAB 6: SOD Conflicts
  // ─────────────────────────────────────────────
  const sheet4 = workbook.addWorksheet("SOD Conflicts");
  sheet4.columns = [
    { header: "User", key: "userName", width: 25 },
    { header: "Severity", key: "severity", width: 12 },
    { header: "Rule", key: "ruleName", width: 25 },
    { header: "Permission A", key: "permissionIdA", width: 15 },
    { header: "Permission B", key: "permissionIdB", width: 15 },
    { header: "Resolution", key: "resolutionStatus", width: 15 },
    { header: "Notes", key: "resolutionNotes", width: 40 },
  ];

  const conflicts = db.select({
    userName: schema.users.displayName,
    severity: schema.sodConflicts.severity,
    ruleName: schema.sodRules.ruleName,
    permissionIdA: schema.sodConflicts.permissionIdA,
    permissionIdB: schema.sodConflicts.permissionIdB,
    resolutionStatus: schema.sodConflicts.resolutionStatus,
    resolutionNotes: schema.sodConflicts.resolutionNotes,
  })
    .from(schema.sodConflicts)
    .innerJoin(schema.users, eq(schema.users.id, schema.sodConflicts.userId))
    .innerJoin(schema.sodRules, eq(schema.sodRules.id, schema.sodConflicts.sodRuleId))
    .all();

  for (const c of conflicts) {
    sheet4.addRow(c);
  }
  styleHeader(sheet4);

  // ─────────────────────────────────────────────
  // TAB 7: Permission Gaps
  // ─────────────────────────────────────────────
  const sheet5 = workbook.addWorksheet("Permission Gaps");
  sheet5.columns = [
    { header: "Persona", key: "personaName", width: 25 },
    { header: "Permission ID", key: "permissionId", width: 15 },
    { header: "Permission Name", key: "permissionName", width: 25 },
    { header: "Gap Type", key: "gapType", width: 15 },
    { header: "Notes", key: "notes", width: 40 },
  ];

  const gapRows = db.select({
    personaName: schema.personas.name,
    permissionId: schema.sourcePermissions.permissionId,
    permissionName: schema.sourcePermissions.permissionName,
    gapType: schema.permissionGaps.gapType,
    notes: schema.permissionGaps.notes,
  })
    .from(schema.permissionGaps)
    .innerJoin(schema.personas, eq(schema.personas.id, schema.permissionGaps.personaId))
    .innerJoin(schema.sourcePermissions, eq(schema.sourcePermissions.id, schema.permissionGaps.sourcePermissionId))
    .all();

  for (const g of gapRows) {
    sheet5.addRow(g);
  }
  styleHeader(sheet5);

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

function styleHeader(sheet: ExcelJS.Worksheet) {
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF4F46E5" }, // Indigo — brand primary
  };
  headerRow.alignment = { vertical: "middle" };
  headerRow.height = 24;

  // Freeze header row
  sheet.views = [{ state: "frozen", ySplit: 1 }];

  // Alternating row colors for readability
  const rowCount = sheet.rowCount;
  for (let i = 2; i <= rowCount; i++) {
    const row = sheet.getRow(i);
    if (i % 2 === 0) {
      row.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFF8FAFC" }, // Slate 50
      };
    }
    // Light borders
    row.eachCell((cell) => {
      cell.border = {
        bottom: { style: "thin", color: { argb: "FFE2E8F0" } },
      };
    });
  }

  // Auto-filter on header
  if (rowCount > 1) {
    const lastCol = sheet.columnCount;
    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: lastCol },
    };
  }
}
