import PDFDocument from "pdfkit";
import { db } from "@/db";
import * as schema from "@/db/schema";
import { count, eq } from "drizzle-orm";

export async function generatePdfReport(generatedByUsername?: string): Promise<Buffer> {
  // Query stats — all async before entering the sync PDF builder
  const [totalUsersRow] = await db.select({ count: count() }).from(schema.users);
  const totalUsers = totalUsersRow!.count;
  const [totalPersonasRow] = await db.select({ count: count() }).from(schema.personas);
  const totalPersonas = totalPersonasRow!.count;
  const [totalTargetRolesRow] = await db.select({ count: count() }).from(schema.targetRoles);
  const totalTargetRoles = totalTargetRolesRow!.count;
  const [totalAssignmentsRow] = await db.select({ count: count() }).from(schema.userTargetRoleAssignments);
  const totalAssignments = totalAssignmentsRow!.count;
  const [approvedRow] = await db.select({ count: count() }).from(schema.userTargetRoleAssignments)
    .where(eq(schema.userTargetRoleAssignments.status, "approved"));
  const approved = approvedRow!.count;
  const [totalMappingsRow] = await db.select({ count: count() }).from(schema.personaTargetRoleMappings);
  const totalMappings = totalMappingsRow!.count;
  const [conflictsRow] = await db.select({ count: count() }).from(schema.sodConflicts);
  const conflicts = conflictsRow!.count;
  const approvalPct = totalAssignments > 0 ? Math.round((approved / totalAssignments) * 100) : 0;

  const deptStats = await db.select({
    department: schema.users.department,
    userCount: count(),
  }).from(schema.users).groupBy(schema.users.department);

  const allConflictRows = conflicts > 0
    ? await db.select().from(schema.sodConflicts)
    : [];

  const personas = await db.select().from(schema.personas);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ─────────────────────────────────────────────
    // COVER PAGE
    // ─────────────────────────────────────────────
    doc.moveDown(4);
    doc.fontSize(28).font("Helvetica-Bold").text("PROVISUM", { align: "center" });
    doc.fontSize(12).font("Helvetica").fillColor("#64748B").text("Enterprise Role Migration Platform", { align: "center" });
    doc.moveDown(2);
    doc.fillColor("#000000");
    doc.fontSize(20).font("Helvetica-Bold").text("Role Mapping Audit Report", { align: "center" });
    doc.moveDown(1);

    // Branded accent line (indigo)
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#4F46E5").lineWidth(2).stroke();
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#14B8A6").lineWidth(1).stroke();
    doc.moveDown(1);

    doc.fontSize(11).font("Helvetica");
    doc.text(`Report Generated: ${new Date().toLocaleString()}`, { align: "center" });
    if (generatedByUsername) {
      doc.text(`Generated By: ${generatedByUsername}`, { align: "center" });
    }
    doc.moveDown(2);

    // Project summary box
    doc.fontSize(14).font("Helvetica-Bold").text("Project Summary", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");
    doc.text(`Total Users: ${totalUsers}`, { align: "center" });
    doc.text(`Personas Generated: ${totalPersonas}`, { align: "center" });
    doc.text(`Total Mappings: ${totalMappings}`, { align: "center" });
    doc.text(`Target Roles: ${totalTargetRoles}`, { align: "center" });
    doc.text(`Total Role Assignments: ${totalAssignments}`, { align: "center" });
    doc.text(`Approved Assignments: ${approved}`, { align: "center" });
    doc.text(`Approval Rate: ${approvalPct}%`, { align: "center" });
    doc.text(`SOD Conflicts Detected: ${conflicts}`, { align: "center" });

    // ─────────────────────────────────────────────
    // EXECUTIVE SUMMARY (new page)
    // ─────────────────────────────────────────────
    doc.addPage();
    doc.fontSize(20).font("Helvetica-Bold").fillColor("#4F46E5").text("Executive Summary");
    doc.fillColor("#000000");
    doc.moveDown(1);

    // Key metrics
    doc.fontSize(14).font("Helvetica-Bold").text("Key Metrics");
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");

    const metricsData = [
      { label: "Users Loaded", value: totalUsers, status: totalUsers > 0 ? "Complete" : "Pending" },
      { label: "Personas Generated", value: totalPersonas, status: totalPersonas > 0 ? "Complete" : "Pending" },
      { label: "Role Mappings", value: totalMappings, status: totalMappings > 0 ? "Complete" : "Pending" },
      { label: "Total Assignments", value: totalAssignments, status: totalAssignments > 0 ? "Complete" : "Pending" },
      { label: "Approved Assignments", value: approved, status: approvalPct >= 80 ? "On Track" : "In Progress" },
      { label: "Approval Rate", value: `${approvalPct}%`, status: approvalPct >= 80 ? "Healthy" : approvalPct >= 50 ? "Moderate" : "Needs Attention" },
    ];

    for (const m of metricsData) {
      doc.text(`${m.label}: ${m.value} (${m.status})`);
    }
    doc.moveDown(1.5);

    // Department breakdown
    doc.fontSize(14).font("Helvetica-Bold").text("Department Breakdown");
    doc.moveDown(0.5);

    doc.fontSize(11).font("Helvetica");
    for (const dept of deptStats) {
      const pct = totalUsers > 0 ? Math.round((dept.userCount / totalUsers) * 100) : 0;
      doc.text(`${dept.department ?? "Unknown"}: ${dept.userCount} users (${pct}%)`);
    }
    doc.moveDown(1.5);

    // Risk summary — SOD conflicts by severity
    doc.fontSize(14).font("Helvetica-Bold").text("Risk Summary \u2014 SOD Conflicts by Severity");
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");

    if (conflicts === 0) {
      doc.text("No SOD conflicts detected. Risk level: LOW.");
    } else {
      const severityMap: Record<string, { total: number; open: number; accepted: number }> = {};
      for (const c of allConflictRows) {
        const sev = c.severity ?? "unknown";
        if (!severityMap[sev]) severityMap[sev] = { total: 0, open: 0, accepted: 0 };
        severityMap[sev].total++;
        if (c.resolutionStatus === "open") severityMap[sev].open++;
        if (c.resolutionStatus === "risk_accepted") severityMap[sev].accepted++;
      }
      for (const [sev, stats] of Object.entries(severityMap)) {
        const statusParts: string[] = [];
        if (stats.open > 0) statusParts.push(`${stats.open} open`);
        if (stats.accepted > 0) statusParts.push(`${stats.accepted} accepted`);
        const resolved = stats.total - stats.open - stats.accepted;
        if (resolved > 0) statusParts.push(`${resolved} resolved`);
        doc.text(`${sev.charAt(0).toUpperCase() + sev.slice(1)}: ${stats.total} conflicts (${statusParts.join(", ")})`);
      }

      const totalOpen = allConflictRows.filter(c => c.resolutionStatus === "open").length;
      const totalAccepted = allConflictRows.filter(c => c.resolutionStatus === "risk_accepted").length;
      doc.moveDown(0.5);
      doc.font("Helvetica-Bold").text(
        `Overall Risk Level: ${totalOpen > 0 ? "HIGH" : totalAccepted > 0 ? "MEDIUM" : "LOW"}`
      );
      doc.font("Helvetica");
    }

    // ─────────────────────────────────────────────
    // DETAIL SECTIONS (existing content, on new pages)
    // ─────────────────────────────────────────────
    doc.addPage();
    doc.fontSize(16).font("Helvetica-Bold").fillColor("#4F46E5").text("Persona Summary");
    doc.fillColor("#000000");
    doc.moveDown(0.5);

    doc.fontSize(11).font("Helvetica");
    for (const p of personas) {
      doc.text(`${p.name} \u2014 ${p.businessFunction ?? "General"} (${p.source})`);
    }

    // Add branded footer to all pages
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      const pageNum = i + 1;
      const totalPages = range.count;

      // Footer divider
      doc.moveTo(50, doc.page.height - 60).lineTo(doc.page.width - 50, doc.page.height - 60)
        .strokeColor("#E2E8F0").lineWidth(0.5).stroke();

      // Footer text
      doc.fontSize(8).font("Helvetica").fillColor("#94A3B8");
      doc.text(
        "Provisum — Intelligent Role Mapping for Enterprise Migrations",
        50, doc.page.height - 50,
        { width: 300, align: "left" }
      );
      doc.text(
        `Page ${pageNum} of ${totalPages}`,
        doc.page.width - 150, doc.page.height - 50,
        { width: 100, align: "right" }
      );
      doc.fillColor("#000000"); // Reset
    }

    doc.end();
  });
}
