import PDFDocument from "pdfkit";
import { db } from "@/db";
import * as schema from "@/db/schema";
import { count, eq } from "drizzle-orm";

export async function generatePdfReport(generatedByUsername?: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Query stats
    const totalUsers = db.select({ count: count() }).from(schema.users).get()!.count;
    const totalPersonas = db.select({ count: count() }).from(schema.personas).get()!.count;
    const totalTargetRoles = db.select({ count: count() }).from(schema.targetRoles).get()!.count;
    const totalAssignments = db.select({ count: count() }).from(schema.userTargetRoleAssignments).get()!.count;
    const approved = db.select({ count: count() }).from(schema.userTargetRoleAssignments)
      .where(eq(schema.userTargetRoleAssignments.status, "approved")).get()!.count;
    const totalMappings = db.select({ count: count() }).from(schema.personaTargetRoleMappings).get()!.count;
    const conflicts = db.select({ count: count() }).from(schema.sodConflicts).get()!.count;
    const approvalPct = totalAssignments > 0 ? Math.round((approved / totalAssignments) * 100) : 0;

    // ─────────────────────────────────────────────
    // COVER PAGE
    // ─────────────────────────────────────────────
    doc.moveDown(4);
    doc.fontSize(28).font("Helvetica-Bold").text("PROVISUM", { align: "center" });
    doc.fontSize(12).font("Helvetica").fillColor("#64748B").text("Enterprise Role Migration Platform", { align: "center" });
    doc.moveDown(2);
    doc.fillColor("#000000");
    doc.fontSize(20).font("Helvetica-Bold").text("Role Mapping Audit Report", { align: "center" });
    doc.moveDown(1);

    // Divider line
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#CBD5E1").stroke();
    doc.moveDown(1);

    doc.fontSize(11).font("Helvetica");
    doc.text(`Report Generated: ${new Date().toLocaleString()}`, { align: "center" });
    if (generatedByUsername) {
      doc.text(`Generated By: ${generatedByUsername}`, { align: "center" });
    }
    doc.moveDown(2);

    // Project summary box
    doc.fontSize(14).font("Helvetica-Bold").text("Project Summary", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");
    doc.text(`Total Users: ${totalUsers}`, { align: "center" });
    doc.text(`Personas Generated: ${totalPersonas}`, { align: "center" });
    doc.text(`Total Mappings: ${totalMappings}`, { align: "center" });
    doc.text(`Target Roles: ${totalTargetRoles}`, { align: "center" });
    doc.text(`Total Role Assignments: ${totalAssignments}`, { align: "center" });
    doc.text(`Approved Assignments: ${approved}`, { align: "center" });
    doc.text(`Approval Rate: ${approvalPct}%`, { align: "center" });
    doc.text(`SOD Conflicts Detected: ${conflicts}`, { align: "center" });

    // ─────────────────────────────────────────────
    // EXECUTIVE SUMMARY (new page)
    // ─────────────────────────────────────────────
    doc.addPage();
    doc.fontSize(20).font("Helvetica-Bold").text("Executive Summary");
    doc.moveDown(1);

    // Key metrics
    doc.fontSize(14).font("Helvetica-Bold").text("Key Metrics");
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");

    const metricsData = [
      { label: "Users Loaded", value: totalUsers, status: totalUsers > 0 ? "Complete" : "Pending" },
      { label: "Personas Generated", value: totalPersonas, status: totalPersonas > 0 ? "Complete" : "Pending" },
      { label: "Role Mappings", value: totalMappings, status: totalMappings > 0 ? "Complete" : "Pending" },
      { label: "Total Assignments", value: totalAssignments, status: totalAssignments > 0 ? "Complete" : "Pending" },
      { label: "Approved Assignments", value: approved, status: approvalPct >= 80 ? "On Track" : "In Progress" },
      { label: "Approval Rate", value: `${approvalPct}%`, status: approvalPct >= 80 ? "Healthy" : approvalPct >= 50 ? "Moderate" : "Needs Attention" },
    ];

    for (const m of metricsData) {
      doc.text(`${m.label}: ${m.value} (${m.status})`);
    }
    doc.moveDown(1.5);

    // Department breakdown
    doc.fontSize(14).font("Helvetica-Bold").text("Department Breakdown");
    doc.moveDown(0.5);

    const deptStats = db.select({
      department: schema.users.department,
      userCount: count(),
    }).from(schema.users).groupBy(schema.users.department).all();

    doc.fontSize(11).font("Helvetica");
    for (const dept of deptStats) {
      const pct = totalUsers > 0 ? Math.round((dept.userCount / totalUsers) * 100) : 0;
      doc.text(`${dept.department ?? "Unknown"}: ${dept.userCount} users (${pct}%)`);
    }
    doc.moveDown(1.5);

    // Risk summary — SOD conflicts by severity
    doc.fontSize(14).font("Helvetica-Bold").text("Risk Summary \u2014 SOD Conflicts by Severity");
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");

    if (conflicts === 0) {
      doc.text("No SOD conflicts detected. Risk level: LOW.");
    } else {
      const allConflictRows = db.select().from(schema.sodConflicts).all();
      const severityMap: Record<string, { total: number; open: number; accepted: number }> = {};
      for (const c of allConflictRows) {
        const sev = c.severity ?? "unknown";
        if (!severityMap[sev]) severityMap[sev] = { total: 0, open: 0, accepted: 0 };
        severityMap[sev].total++;
        if (c.resolutionStatus === "open") severityMap[sev].open++;
        if (c.resolutionStatus === "risk_accepted") severityMap[sev].accepted++;
      }
      for (const [sev, stats] of Object.entries(severityMap)) {
        const statusParts: string[] = [];
        if (stats.open > 0) statusParts.push(`${stats.open} open`);
        if (stats.accepted > 0) statusParts.push(`${stats.accepted} accepted`);
        const resolved = stats.total - stats.open - stats.accepted;
        if (resolved > 0) statusParts.push(`${resolved} resolved`);
        doc.text(`${sev.charAt(0).toUpperCase() + sev.slice(1)}: ${stats.total} conflicts (${statusParts.join(", ")})`);
      }

      const totalOpen = allConflictRows.filter(c => c.resolutionStatus === "open").length;
      const totalAccepted = allConflictRows.filter(c => c.resolutionStatus === "risk_accepted").length;
      doc.moveDown(0.5);
      doc.font("Helvetica-Bold").text(
        `Overall Risk Level: ${totalOpen > 0 ? "HIGH" : totalAccepted > 0 ? "MEDIUM" : "LOW"}`
      );
      doc.font("Helvetica");
    }

    // ─────────────────────────────────────────────
    // DETAIL SECTIONS (existing content, on new pages)
    // ─────────────────────────────────────────────
    doc.addPage();
    doc.fontSize(16).font("Helvetica-Bold").text("Persona Summary");
    doc.moveDown(0.5);

    const personas = db.select().from(schema.personas).all();
    doc.fontSize(11).font("Helvetica");
    for (const p of personas) {
      doc.text(`${p.name} \u2014 ${p.businessFunction ?? "General"} (${p.source})`);
    }

    doc.end();
  });
}
